title: <p align="center"> Somasundaram S. </p>

logo: "/images/Som_32.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/Resume - Somasundaram S..pdf">Resume </a> |
  <a href="https://www.linkedin.com/in/somasundaram-shanmugasundaram-7375a7a2/">LinkedIn</a> |
  <a href="https://github.com/somasundaram1702">GitHub</a>
  </p>
  
  <p align="justify">
  I am curretly working as a datascientist at eInfochips
  <br><br>  
  Interested in solving problems using deep learning and machine learning techniques
  <br><br>
  </p>

title: "Somasundaram S."
output: 
  html_document:
    includes:
       in_header: analytics.html
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID

google_analytics: G-H9HN0M3497
