title: <p align="center"> Somasundaram S. </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chriskhanhtran/">LinkedIn</a> |
  <a href="https://github.com/somasundaram1702">GitHub</a>
  </p>
  
  <p align="justify">
  I am curretly working as a datascientist at eInfochips
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
