title: <p align="center"> Somasundaram S. </p>

logo: "/images/som1.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume </a> |
  <a href="https://www.linkedin.com/in/somasundaram-shanmugasundaram-7375a7a2/">LinkedIn</a> |
  <a href="https://github.com/somasundaram1702">GitHub</a>
  </p>
  
  <p align="justify">
  I am curretly working as a datascientist at eInfochips
  <br><br>  
  Interested in solving problems using deep learning and machine learning techniques
  <br><br>
  </p>

  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
